pipeline{
    agent any

    stages{
        stage("Deploy"){
            steps {
                sh '''
                    oc project fhulvf-deploy-strategies
                    oc start-build greeting-service --follow --wait
                '''
            }
        }
    }
}
